services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: development 
      POSTGRES_USER: postgres
      POSTGRES_DB: waiter
    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports:
      - 5432:5432
    networks:
        - pg-network
volumes:
  pgdata:

networks:
  pg-network:
    external: true
