@Waiter.API_HostAddress = https://localhost:7247/api

@Email = admin@uchoamp.dev
@Password = Administrator1!

@AccessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTkzNjUyYi1iNWQxLTdkNmYtYTQ3Yy00ZWEwNGQ3NTMyNDgiLCJuYW1laWQiOiIwMTkzNjUyYi1iNWQxLTdkNmYtYTQ3Yy00ZWEwNGQ3NTMyNDgiLCJyb2xlIjoiYWRtaW4iLCJuYmYiOjE3MzI2NjU0MzAsImV4cCI6Mzc3MzI2NjU0MzAsImlhdCI6MTczMjY2NTQzMH0.kuYmtdPzAh5-tKV0QDct4hbZshC4f5xg3fgQVQdDze0


POST {{Waiter.API_HostAddress}}/users/authorize
Content-Type: application/json
{
  "email": "{{Email}}",
  "password": "{{Password}}"
}

###

GET {{Waiter.API_HostAddress}}/users/available-roles
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

###

POST {{Waiter.API_HostAddress}}/users
Content-Type: application/json
Authorization: Bearer {{AccessToken}}
{
  "firstName": "Marcos",
  "lastName": "Pacheco",
  "email": "pacheco@uchoamp.dev",
  "password": "Pass1234!",
  "phoneNumber": "86981732880",
  "roles": [
    "admin"
  ]
}

###

GET {{Waiter.API_HostAddress}}/users
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

###

GET {{Waiter.API_HostAddress}}/users/01936a3b-c458-705f-953d-36b98e4bed95
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

###

PUT {{Waiter.API_HostAddress}}/users
Content-Type: application/json
Authorization: Bearer {{AccessToken}}
{
  "id": "01936b96-991d-77bc-b66d-9491bc058567",
  "firstName": "Marcos",
  "lastName": "Uchoa",
  "email": "marcos@uchoamp.dev",
  "phoneNumber": "86981732880"
}

###

DELETE {{Waiter.API_HostAddress}}/users/01936a3b-c458-705f-953d-36b98e4bed95
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

###

POST {{Waiter.API_HostAddress}}/customers
Content-Type: application/json
Authorization: Bearer {{AccessToken}}
{
  "firstName": "Marcos",
  "lastName": "Uchoa",
  "phoneNumber": "8881732889"
}

###

GET {{Waiter.API_HostAddress}}/customers?page=1&pageSize=10
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

###

GET {{Waiter.API_HostAddress}}/customers/01937045-071e-7aea-9eb4-3982ffdf003d
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

###

PUT {{Waiter.API_HostAddress}}/customers/01937045-071e-7aea-9eb4-3982ffdf003d
Content-Type: application/json
Authorization: Bearer {{AccessToken}}
{
  "firstName": "Foo",
  "lastName": "Bar",
  "phoneNumber": "(88) 98173-2880"
}

###

DELETE {{Waiter.API_HostAddress}}/customers/01937040-3235-72e2-9b03-3cbe481cc2c0
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

###

POST {{Waiter.API_HostAddress}}/menuItems
Content-Type: application/json
Authorization: Bearer {{AccessToken}}
{
  "Name": "Item 2",
  "PriceCents": 10
}

###

GET {{Waiter.API_HostAddress}}/menuItems?page=1&pageSize=10
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

###

GET {{Waiter.API_HostAddress}}/menuItems/0193711a-4daa-748a-8a30-686fa02c5ca6
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

###

PUT {{Waiter.API_HostAddress}}/menuItems/0193711a-4daa-748a-8a30-686fa02c5ca6
Content-Type: application/json
Authorization: Bearer {{AccessToken}}
{
  "name": "New Item 2",
  "priceCents": 50
}

###

DELETE {{Waiter.API_HostAddress}}/menuItems/01937119-d151-7380-92b0-7c5b97b5681a
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

###

POST {{Waiter.API_HostAddress}}/orders
Content-Type: application/json
Authorization: Bearer {{AccessToken}}
{
  "customerId": "01937045-071e-7aea-9eb4-3982ffdf003d",
  "items": [
    {
      "itemId": "0193711a-4daa-748a-8a30-686fa02c5ca6",
      "quantity": 1
    }
  ]
}

###

GET {{Waiter.API_HostAddress}}/orders?page=1&pageSize=10
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

###

GET {{Waiter.API_HostAddress}}/orders/0193743f-c074-75df-9526-7cffb7f4aa59
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

###

PUT {{Waiter.API_HostAddress}}/orders/0193743f-c074-75df-9526-7cffb7f4aa59
Content-Type: application/json
Authorization: Bearer {{AccessToken}}
{
  "customerId": "01937003-3aaf-7270-81f2-df99e7484ff8",
  "items": [
    {
      "itemId": "01937437-75e6-7523-8b0e-86b035787135",
      "quantity": 10
    },
    {
      "itemId": "0193711a-4daa-748a-8a30-686fa02c5ca6",
      "quantity": 2 
    }
  ]
}


###

DELETE {{Waiter.API_HostAddress}}/orders/01937426-1c35-7c73-9d80-a86b91afc7da
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

###

PATCH {{Waiter.API_HostAddress}}/orders/0193749d-1bff-7005-b61d-e9d4ffdbd8a1/status?status=3
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

###

POST {{Waiter.API_HostAddress}}/CustomerOrders
Content-Type: application/json
{
  "firstName": "Foo",
  "lastName": "Baar",
  "phoneNumber": "99991732880",
  "items": [
    {
      "itemId": "01937437-75e6-7523-8b0e-86b035787135",
      "quantity": 1
    }
  ]
}
