@Waiter.API_HostAddress = https://localhost:7247/api

@Email = admin@uchoamp.dev
@Password = Administrator1!

@AccessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTkzNjUyYi1iNWQxLTdkNmYtYTQ3Yy00ZWEwNGQ3NTMyNDgiLCJuYW1laWQiOiIwMTkzNjUyYi1iNWQxLTdkNmYtYTQ3Yy00ZWEwNGQ3NTMyNDgiLCJyb2xlIjoiYWRtaW4iLCJuYmYiOjE3MzI2NTM4NDYsImV4cCI6MTczMjY1NzQ0NiwiaWF0IjoxNzMyNjUzODQ2fQ.7x0eh7MvcPNOZFNLl-MEWzwq6kkb4MTEiid0PdHZwUQ


POST {{Waiter.API_HostAddress}}/users/authorize
Content-Type: application/json
{
  "email": "{{Email}}",
  "password": "{{Password}}"
}

###

GET {{Waiter.API_HostAddress}}/users/available-roles
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

###

POST {{Waiter.API_HostAddress}}/users
Content-Type: application/json
Authorization: Bearer {{AccessToken}}
{
  "firstName": "Marcos",
  "lastName": "Uchoa",
  "email": "marcos@uchoamp.dev",
  "password": "Pass1234!",
  "roles": [
    "admin"
  ]
}

###

GET {{Waiter.API_HostAddress}}/users
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

###

GET {{Waiter.API_HostAddress}}/users/1
Content-Type: application/json


###




